### ISSUE TITLE
Create a .gitignore file

### ISSUE THREAD

**Issue by dibarra-nest** [bizznest-dev/collaboration-repository#2]
#### Description
The repository contains sensitive information in the `.env` file. Let's prevent tracking of this file by creating a `.gitignore` entry and remove the `.env` file from the repository.

#### Tasks
- [ ] Create a `.gitignore` file if not present.
- [ ] Add an entry to ignore the `.env` file.
- [ ] Remove the `.env` file from the repository.

#### Additional Information
The `.env` file contains sensitive data and should not be publicly tracked in version control to maintain security.

#### Steps
1. Check for an existing `.gitignore` file.
2. Update `.gitignore` to exclude `.env`.
3. Remove `.env` file from the repository.
